# execfile('bodybuilding/tests/addDummyWeightliftingData.py')

import datetime
from django.utils import timezone
from bodybuilding.models import Weightlifting

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now(), set = 1, weight = 50, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now(), set = 2, weight = 55, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now(), set = 3, weight = 60, reps = 5)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now(), set = 4, weight = 40, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=1), set = 1, weight = 50, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=1), set = 2, weight = 55, reps = 9)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=1), set = 3, weight = 60, reps = 4)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=1), set = 4, weight = 40, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=2), set = 1, weight = 50, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=2), set = 2, weight = 60, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=2), set = 3, weight = 60, reps = 4)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=2), set = 4, weight = 40, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=3), set = 1, weight = 55, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=3), set = 2, weight = 60, reps = 7)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=3), set = 3, weight = 65, reps = 3)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=4), set = 1, weight = 55, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=4), set = 2, weight = 60, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=4), set = 3, weight = 65, reps = 5)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=4), set = 4, weight = 40, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=5), set = 1, weight = 60, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=5), set = 2, weight = 65, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=5), set = 3, weight = 65, reps = 5)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=5), set = 4, weight = 40, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=6), set = 1, weight = 60, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=6), set = 2, weight = 65, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=6), set = 3, weight = 70, reps = 4)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellBenchPress', date = timezone.now() + datetime.timedelta(days=6), set = 4, weight = 40, reps = 5)
dbbp.save()


dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now(), set = 1, weight = 25, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now(), set = 2, weight = 25, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now(), set = 3, weight = 30, reps = 5)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now(), set = 4, weight = 20, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=1), set = 1, weight = 25, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=1), set = 2, weight = 30, reps = 9)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=1), set = 3, weight = 35, reps = 4)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=1), set = 4, weight = 25, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=2), set = 1, weight = 25, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=2), set = 2, weight = 30, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=2), set = 3, weight = 35, reps = 4)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=2), set = 4, weight = 25, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=3), set = 1, weight = 30, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=3), set = 2, weight = 35, reps = 7)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=3), set = 3, weight = 40, reps = 3)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=4), set = 1, weight = 30, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=4), set = 2, weight = 35, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=4), set = 3, weight = 40, reps = 5)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=4), set = 4, weight = 30, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=5), set = 1, weight = 35, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=5), set = 2, weight = 40, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=5), set = 3, weight = 40, reps = 5)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=5), set = 4, weight = 35, reps = 5)
dbbp.save()

dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=6), set = 1, weight = 40, reps = 12)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=6), set = 2, weight = 45, reps = 8)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=6), set = 3, weight = 50, reps = 4)
dbbp.save()
dbbp = Weightlifting(exercise = 'DumbbellCurl', date = timezone.now() + datetime.timedelta(days=6), set = 4, weight = 35, reps = 5)
dbbp.save()
