# Generated by Django 4.1.2 on 2023-10-02 04:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('file', models.FileField(upload_to='clips')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ClipTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clips.clip')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clips.tag')),
            ],
        ),
    ]
