# Generated by Django 4.1.2 on 2022-11-28 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('name_slug', models.SlugField(max_length=128)),
                ('text', models.TextField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.note')),
            ],
        ),
    ]
