# Generated by Django 4.1.2 on 2022-12-12 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_tag_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/notes'),
        ),
    ]
