# Generated by Django 4.1.2 on 2024-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_text_file_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
