# Generated by Django 4.0.5 on 2022-06-19 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeightExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('startTime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('endTime', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WeightTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodybuilding.weightexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodybuilding.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reps', models.PositiveSmallIntegerField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodybuilding.weighttraining')),
            ],
        ),
        migrations.CreateModel(
            name='CardioTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('units', models.CharField(max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodybuilding.cardioexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodybuilding.workoutsession')),
            ],
        ),
    ]
