# Generated by Django 4.1.2 on 2022-11-24 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('name_slug', models.SlugField(max_length=128)),
                ('ingredient_text', models.TextField(max_length=8192)),
                ('direction_text', models.TextField(max_length=8192)),
            ],
        ),
    ]
