# Generated by Django 4.0.5 on 2022-07-03 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('ingredientsText', models.TextField(max_length=8192)),
                ('directionsText', models.TextField(max_length=8192)),
            ],
        ),
    ]
