# Generated by Django 4.0.5 on 2022-07-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slugName',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
